# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bolt < Formula
  desc "Developer Swiss Army Knife CLI"
  homepage "https://github.com/AkshayS96/bolt"
  version "4.4.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AkshayS96/bolt/releases/download/v4.4.6/bolt_4.4.6_darwin_amd64.tar.gz"
      sha256 "c51127cac39e80c83022b704def874c896a602784d1ebc509282de60f8edcea2"

      define_method(:install) do
        bin.install "bolt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AkshayS96/bolt/releases/download/v4.4.6/bolt_4.4.6_darwin_arm64.tar.gz"
      sha256 "bfeccb0f87e623bcb2184902c51750c7fdf12baa76aa1dfa8c892d979c9a887e"

      define_method(:install) do
        bin.install "bolt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AkshayS96/bolt/releases/download/v4.4.6/bolt_4.4.6_linux_amd64.tar.gz"
      sha256 "6a1b126fc26c8d22e769a389d049064dc6d13671267bc0e1cb7a223776a03a1d"
      define_method(:install) do
        bin.install "bolt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AkshayS96/bolt/releases/download/v4.4.6/bolt_4.4.6_linux_arm64.tar.gz"
      sha256 "eb4a1b833fc90b1cd2536ef5f7ba6285a7e825f397bee1270579573d32b40a00"
      define_method(:install) do
        bin.install "bolt"
      end
    end
  end
end
